### ISSUE TITLE
Додати можливість коментувати статті (дописи)

### ISSUE THREAD

**Issue by vk0xOrg** [uanet-exception/exception.net.ua#3]
Пропоную додати можливість коментувати статті. Хуго пропонує ряд технологій, як на мене цікавими є
- [utterances](https://utteranc.es/)
- [Remark42](https://remark42.com/)
- [Isso](https://posativ.org/isso/)
- [Cactus Comments](https://cactus.chat/docs/integrations/hugo/)

**Comment by zen-tools** [comment]
Додав підтримку utterances
